/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI.chill;

import com.pro1e.UI.MainF;
import com.pro1e.UI.QLnhiemvu;
import com.pro1e.UI.chill.*;
import com.pro1e.utils.Xfile;
import com.pro1e.utils.auth;
import com.pro1e.utils.magbox;
import duan1.model.SuKien;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.event.AncestorListener;

/**
 *
 * @author huyNQph11019
 */
public class functionIcon extends javax.swing.JPanel implements ActionListener {
    
    private JPanel chucNang, parent;
    MainF root;
    SuKien ev;

    /**
     * Creates new form functionIcon
     */
    public functionIcon(String pathimg, String tenCN, MainF pa) { // tham số đầu vào là root mainf, và pannel chức năng 

        this.root = pa;
        
        initComponents();
        intnit(tenCN, Xfile.read(pathimg));  // đọc file qua đường dẫn
        lbicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showcn(evt);
            }
        });
        
    }
    
    public functionIcon(String TenchucNang, MainF root, SuKien ev) { // gán chức năng theo form jpannel qNV
      
        initComponents();
        this.ev = ev;
        this.root = root;
        
//        this.lbicon = Xfile.read("đường dẫn ");
        this.lbtencn.setText(TenchucNang);  
         lbicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showcn(evt);
            }
        });
    }
    
   
    
  
    
    public void intnit(String tencn, ImageIcon icon) {
        lbtencn.setText(tencn);
        lbicon.setIcon(icon);
//        lbicon.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                showcn(evt);
//            }
//        });
    }
    
    public void showcn(java.awt.event.MouseEvent evt) {
        auth.curSUKIEN = ev;
        root.openForm(new QLnhiemvu());
    }
//    ImageIcon iconF (String path){
//        try {
//          ImageIcon f = Xfile.read(path);
//          return f;
//        } catch (Exception e) {
//            throw new RuntimeException();
//        }
//   
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        lbicon = new javax.swing.JLabel();
        lbtencn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 128, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        setPreferredSize(new java.awt.Dimension(200, 100));
        setLayout(new java.awt.BorderLayout());

        lbicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_ios_development_50px.png"))); // NOI18N
        add(lbicon, java.awt.BorderLayout.CENTER);

        lbtencn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtencn.setForeground(new java.awt.Color(255, 255, 255));
        lbtencn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtencn.setText("CHỨC NĂNG");
        add(lbtencn, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbicon;
    private javax.swing.JLabel lbtencn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
