/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI.chill;

import com.pro1e.utils.magbox;
import duan1.model.Comment;
import java.awt.Color;

/**
 *
 * @author huyNQph11019
 */
public class tagcomment extends javax.swing.JPanel {

    /**
     * Creates new form tagcomment
     */
    Comment aCMT;
    public tagcomment(Comment cmt) {
        initComponents();
        this.aCMT = cmt;
        filPN(cmt);
    }
    void filPN(Comment cm){
        lbtenguoicm.setText(cm.getTenNV());
        lbthoigian.setText(cm.getThoigian());
        lbnoidung.setText(cm.getNoiDung());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtenguoicm = new javax.swing.JLabel();
        lbthoigian = new javax.swing.JLabel();
        lbnoidung = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 2, true));
        setPreferredSize(new java.awt.Dimension(560, 60));

        lbtenguoicm.setText("Người CMT");

        lbthoigian.setText("thời gian");

        lbnoidung.setText("nội dung");
        lbnoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnoidungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbnoidungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbnoidungMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbtenguoicm, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 246, Short.MAX_VALUE))
                    .addComponent(lbnoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtenguoicm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbthoigian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbnoidung, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbnoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnoidungMouseClicked
       magbox.mgbox(this, aCMT.getNoiDung());
    }//GEN-LAST:event_lbnoidungMouseClicked

    private void lbnoidungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnoidungMouseEntered
     lbnoidung.setForeground(Color.red);
    }//GEN-LAST:event_lbnoidungMouseEntered

    private void lbnoidungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnoidungMouseExited
       lbnoidung.setForeground(Color.black);
    }//GEN-LAST:event_lbnoidungMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbnoidung;
    private javax.swing.JLabel lbtenguoicm;
    private javax.swing.JLabel lbthoigian;
    // End of variables declaration//GEN-END:variables
}
