/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.UI.chill.functionIcon;
import javax.swing.JFrame;

/**
 *
 * @author huyNQph11019
 */
public class HomeMenu extends javax.swing.JPanel {
MainF pa;
    /**
     * Creates new form HomeMenu
     */
    public HomeMenu(MainF parent) {
        initComponents();
        pa=parent;
//        for (int i = 0; i < 10; i++) {
//             pnbeck.add(new functionIcon("icons8_google_earth_50px.png", "Chức năng A"));
//        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnbeck = new javax.swing.JPanel();
        pnsukien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnsukien1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnsukien2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnsukien3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnsukien4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnsukien5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnsukien6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 640));
        setLayout(new java.awt.BorderLayout());

        pnbeck.setBackground(new java.awt.Color(204, 204, 204));
        pnbeck.setLayout(new java.awt.GridLayout(3, 2));

        pnsukien.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_construction_50px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnsukien.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ SỰ KIỆN");
        pnsukien.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien);

        pnsukien1.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien1.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_reception_50px.png"))); // NOI18N
        pnsukien1.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KHÁCH MỜI");
        pnsukien1.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien1);

        pnsukien2.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien2.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_male_user_50px.png"))); // NOI18N
        pnsukien2.add(jLabel5, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUẢN LÝ NHÂN VIÊN");
        pnsukien2.add(jLabel6, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien2);

        pnsukien3.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien3.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_action_50px.png"))); // NOI18N
        pnsukien3.add(jLabel7, java.awt.BorderLayout.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NHÂN LỰC NGOÀI");
        pnsukien3.add(jLabel8, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien3);

        pnsukien4.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien4.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_pay_by_cash_50px.png"))); // NOI18N
        pnsukien4.add(jLabel9, java.awt.BorderLayout.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("THỐNG KÊ CHI TIÊU");
        pnsukien4.add(jLabel10, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien4);

        pnsukien5.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien5.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_project_50px.png"))); // NOI18N
        pnsukien5.add(jLabel11, java.awt.BorderLayout.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("THỐNG KÊ SỰ KIỆN");
        pnsukien5.add(jLabel12, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien5);

        pnsukien6.setBackground(new java.awt.Color(0, 102, 204));
        pnsukien6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnsukien6.setLayout(new java.awt.BorderLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_settings_50px_1.png"))); // NOI18N
        pnsukien6.add(jLabel13, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CÀI ĐẶT");
        pnsukien6.add(jLabel14, java.awt.BorderLayout.PAGE_END);

        pnbeck.add(pnsukien6);

        jScrollPane1.setViewportView(pnbeck);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       pa.openSUKIEN();
      
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnbeck;
    private javax.swing.JPanel pnsukien;
    private javax.swing.JPanel pnsukien1;
    private javax.swing.JPanel pnsukien2;
    private javax.swing.JPanel pnsukien3;
    private javax.swing.JPanel pnsukien4;
    private javax.swing.JPanel pnsukien5;
    private javax.swing.JPanel pnsukien6;
    // End of variables declaration//GEN-END:variables
}
