/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.DAO.nhiemvuDAO;
import com.pro1e.utils.auth;
import duan1.model.GiaiDoan;
import duan1.model.NhiemVu;
import java.awt.Dimension;
import java.util.List;
import AppPackage.AnimationClass;
import com.pro1e.DAO.GiaidoanDAO;
import com.pro1e.utils.magbox;

/**
 *
 * @author huyNQph11019
 */
public class Pngiaidoan extends javax.swing.JPanel {

//    private AnimationClass amt = new AnimationClass();
    List<NhiemVu> lsnv;
    GiaiDoan gds;
    nhiemvuDAO nvdao = new nhiemvuDAO();
    GiaidoanDAO gdDAO = new GiaidoanDAO();
    public Pngiaidoan(GiaiDoan gd) {
        initComponents();
        this.gds = gd;
        innit(gd);
        loadNVu();

//        for (int i = 0; i < 10; i++) {
//            this.addNV();
//        }
//        this.addNV(new NhiemVu());
//        this.addNV(new NhiemVu());
    }

    void innit(GiaiDoan gd) {
        lbtengd.setText(gd.getTenGD());
        lbbatdau.setText(gd.getNgayBD());
        lbketthuc.setText(gd.getDeadLine());
    }
    int curheight = 0;
    public static int heightpn = 0; //kích thước pannel giai đoạn

    void loadNVu() {
        lsnv = nvdao.selectbysomething(gds.getIdGiaiDoan());
        for (NhiemVu nhiemVu : lsnv) {
            addNV(nhiemVu);
        }

    }

    void addNV(NhiemVu nv) {
        pnlisstNV.add(new Pnnhiemvu(this,nv)); //nhiệm vụ được truyền vào theo list

        heightpn = this.getPreferredSize().height; // kích thước của 1 pannel giai đoạn
        //   pnlisstNV.setSize(800, 150);
        // int h2 = pnlisstNV.getHeight();
        pnlisstNV.setPreferredSize(new Dimension(800, curheight += 110)); // kích thước hiện tại của cái pn list  +110
        this.setPreferredSize(new Dimension(800, heightpn += 110));// kích thức hiện tại của pn giai doạn
        // auth.curqlnhiemvu.setPackmain(800, heightpn);
        pnlisstNV.validate();
        //  System.err.println(h.height);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbtengd = new javax.swing.JLabel();
        tienDo = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbbatdau = new javax.swing.JLabel();
        lbketthuc = new javax.swing.JLabel();
        pnlisstNV = new javax.swing.JPanel();

        setBackground(new java.awt.Color(54, 58, 61));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 55));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 2));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_menu_24px.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(25, 60));
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_delete_bin_24px.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(31, 60));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 120, 60));

        lbtengd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbtengd.setForeground(new java.awt.Color(255, 255, 255));
        lbtengd.setText("Tên giai đoạn");
        add(lbtengd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 30));

        tienDo.setValue(50);
        add(tienDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 10, 370, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm nhiệm vụ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Từ :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đến:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 36, -1, -1));

        lbbatdau.setForeground(new java.awt.Color(255, 255, 255));
        lbbatdau.setText("Ngày bắt đầu");
        add(lbbatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 36, -1, -1));

        lbketthuc.setForeground(new java.awt.Color(255, 255, 255));
        lbketthuc.setText("ngày kết thúc");
        add(lbketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 35, 70, -1));

        pnlisstNV.setBackground(new java.awt.Color(255, 255, 255));
        pnlisstNV.setPreferredSize(new java.awt.Dimension(800, 110));
        pnlisstNV.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 150, 5));
        add(pnlisstNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // tạo nhiệm vụ
        openNhiemvu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged

    }//GEN-LAST:event_jLabel3MouseDragged
    boolean menuY = true;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (menuY) {
            jPanel1.setLocation(730, 0);
            menuY =false;
        } else {
            menuY =true;
            jPanel1.setLocation(780, 0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (magbox.confirm(this, "bạn có chắc chắn muốn xóa giai đoạn này")) {
            if (gdDAO.delete(gds.getIdGiaiDoan())==0 ) {
                magbox.mgbox(this, "không được xóa giai đoạn đang thực hiện");
            }else{
                this.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_jLabel4MouseClicked
    void openNhiemvu() {
//    System.out.println(gds.toString());
        new TAOnhiemvu(this, null, true).setVisible(true); // true == tạo , false ==  update
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbbatdau;
    private javax.swing.JLabel lbketthuc;
    private javax.swing.JLabel lbtengd;
    private javax.swing.JPanel pnlisstNV;
    private javax.swing.JProgressBar tienDo;
    // End of variables declaration//GEN-END:variables
}
