/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.DAO.KhachMoiDAO;
import com.pro1e.DAO.KhachMoiTD_DAO;
import com.pro1e.DAO.SukienDAO;
import com.pro1e.utils.magbox;
import duan1.model.KhachMoi;
import duan1.model.KhachmoiTD;
import duan1.model.SuKien;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyNQph11019
 */
public class pnKhachmoi extends javax.swing.JPanel {

    SukienDAO skDAo = new SukienDAO();
    KhachMoiDAO kmDAO = new KhachMoiDAO();
    KhachMoiTD_DAO kmtdDAO = new KhachMoiTD_DAO();
    List<KhachMoi> lsKhACH;
    DefaultTableModel dftable;
    DefaultComboBoxModel<SuKien> dfSukien;
    int index = 0;

    /**
     * Creates new form pnKhachmoi
     */
    public pnKhachmoi() {
        initComponents();
        lsKhACH = kmDAO.selectall();
        loadKM();
        loadCBsukien();

    }

    void loadKM() {
        dftable = (DefaultTableModel) tba.getModel();
        dftable.setRowCount(0);
        for (KhachMoi khachMoi : lsKhACH) {
            dftable.addRow(new Object[]{
                khachMoi.getTenKM(), khachMoi.getEmail(), khachMoi.getSdt(), khachMoi.getGhiChu()
            });
        }
        tba.setRowSelectionInterval(0, 0);
    }

    void loadCBsukien() {
        List<SuKien> lsSukien = skDAo.selectall();
        dfSukien = (DefaultComboBoxModel) dfsukien.getModel();
        dfSukien.removeAllElements();
        for (SuKien suKien : lsSukien) {
            dfSukien.addElement(suKien);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tba = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cboxMenu = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        dfsukien = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1110, 640));

        tba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên khách mời", "EMAIL", "SDT", "GHI CHÚ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tba);

        txttimkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimkiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttimkiemKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("TÌM KIẾM");

        jButton1.setText("TẠO KHÁCH MỜI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cboxMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MENU", "tạo file excel", "IMPORT EXCEL" }));
        cboxMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxMenuItemStateChanged(evt);
            }
        });
        cboxMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxMenuMouseClicked(evt);
            }
        });

        jButton2.setText("MỜI VÀO SỰ KIỆN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dfsukien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(cboxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dfsukien, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cboxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(dfsukien))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txttimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lsKhACH = kmDAO.timKiemKM(txttimkiem.getText());
            loadKM();
        }
    }//GEN-LAST:event_txttimkiemKeyPressed

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void txttimkiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyTyped
        if (txttimkiem.getText().equals("")) {
            lsKhACH = kmDAO.selectall();
            loadKM();
        }
    }//GEN-LAST:event_txttimkiemKeyTyped

    private void tbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbaMouseClicked
        index = tba.getSelectedRow();
        if (evt.getClickCount() == 2) {
            new TAOkhachmoi(this, lsKhACH.get(index)).setVisible(true);
        }
    }//GEN-LAST:event_tbaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TAOkhachmoi(this, null).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboxMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxMenuItemStateChanged
        int iteam = cboxMenu.getSelectedIndex();
        if (iteam == 1) {
            System.out.println("chọn iteam 1  tạo file excel");
            cboxMenu.setSelectedIndex(0);
        } else if (iteam == 2) {
            System.out.println("chọn iteam 2 inport excel");
            cboxMenu.setSelectedIndex(0);
        }

    }//GEN-LAST:event_cboxMenuItemStateChanged

    private void cboxMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxMenuMouseClicked
//int iteam = cboxMenu.getSelectedIndex();
//        if (iteam == 1) {
//            System.out.println("chọn iteam 1  tạo file excel");
//        } else if (iteam == 2) {
//            System.out.println("chọn iteam 2 inport excel");
//        }
    }//GEN-LAST:event_cboxMenuMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        System.out.println(getKMTD());
        int[] x = tba.getSelectedRows();
        try {
            for (int i : x) {
                kmtdDAO.insert(getKMTD(i));
                System.out.println(getKMTD(i).toString());
            }
        } catch (Exception e) {
            magbox.mgbox(this, "khách mười đã có trong sự kiện");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    KhachmoiTD getKMTD(int row) {
        KhachmoiTD km = new KhachmoiTD();
        SuKien sk = (SuKien) dfSukien.getSelectedItem();
        km.setIdKM(lsKhACH.get(row).getIdKhachMoi());
        km.setIdSK(sk.getIDSK());
        return km;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxMenu;
    private javax.swing.JComboBox<String> dfsukien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tba;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
