/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.DAO.NhanvienDAO;
import com.pro1e.utils.Xdate;
import com.pro1e.utils.magbox;
import duan1.model.NhiemVu;
import duan1.model.NhanVien;
import javax.swing.DefaultComboBoxModel;
import java.util.List;

/**
 *
 * @author huyNQph11019
 */
public class Pnnhiemvu extends javax.swing.JPanel {

    DefaultComboBoxModel<NhanVien> dfcbox;
    List<NhanVien> lsNV;
    NhiemVu nvu;
    Pngiaidoan parent;

    /**
     * Creates new form pnnhiemvu
     */
    public Pnnhiemvu(Pngiaidoan parent, NhiemVu nv) {
        initComponents();
        loadCbox();
        this.nvu = nv;
        this.parent = parent;
        innit(nv);
    }

    void innit(NhiemVu nv) {
        cntennv.setText(nv.getTenNVu());
        if (nv.getMoTa().length() > 50) {
            lbmote.setText(nv.getMoTa().substring(0, 50) + "....");
        } else {
            lbmote.setText(nv.getMoTa());
        }
        System.out.println(nv.getDeaLine());
        jdeadline.setDate(Xdate.todate(nv.getDeaLine(), "yyyy-MM-dd"));

    }

    void loadCbox() {
        lsNV = new NhanvienDAO().selectall();
        dfcbox = (DefaultComboBoxModel) cbthanhvien.getModel();
        dfcbox.removeAllElements();
        lsNV.forEach(nhanVien -> {
            dfcbox.addElement(nhanVien);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cntennv = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lbmote = new javax.swing.JLabel();
        btnreadmore = new javax.swing.JButton();
        jdeadline = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cbthanhvien = new javax.swing.JComboBox<>();
        btnghim = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(153, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        setForeground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 130));
        setPreferredSize(new java.awt.Dimension(800, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cntennv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cntennv.setText("Tên nhiệm vụ");
        add(cntennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 146, -1));

        jLabel1.setText("Miêu tả công việc: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        lbmote.setText("........");
        add(lbmote, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 33, 501, -1));

        btnreadmore.setText("CHI TIẾT");
        btnreadmore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadmoreActionPerformed(evt);
            }
        });
        add(btnreadmore, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 11, -1, 40));
        add(jdeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 200, 30));

        jLabel3.setText("DEAD LINE :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cbthanhvien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbthanhvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 59, 151, 40));

        btnghim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_link_24px.png"))); // NOI18N
        btnghim.setText("ghim file");
        btnghim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghimActionPerformed(evt);
            }
        });
        add(btnghim, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_user_24px_1.png"))); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jProgressBar1.setValue(60);
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 430, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // mở nhiệm vụ chi tiết
        if (evt.getClickCount() == 2) {
            new TAOnhiemvu(parent, nvu, false).setVisible(true);
        }
    }//GEN-LAST:event_formMouseClicked

    private void btnghimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghimActionPerformed
        btnghim.setToolTipText(magbox.prompt(this, "đường dẫn file"));
    }//GEN-LAST:event_btnghimActionPerformed

    private void btnreadmoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadmoreActionPerformed
        new TAOnhiemvu(parent, nvu, false).setVisible(true);
    }//GEN-LAST:event_btnreadmoreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TAOphancong tpc = new TAOphancong();
       tpc.setLocation(this.getX(), this.getY());
       tpc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnghim;
    private javax.swing.JButton btnreadmore;
    private javax.swing.JComboBox<String> cbthanhvien;
    private javax.swing.JCheckBox cntennv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private com.toedter.calendar.JDateChooser jdeadline;
    private javax.swing.JLabel lbmote;
    // End of variables declaration//GEN-END:variables
}
