/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.DAO.NhanvienDAO;
import com.pro1e.helper.JDBChelper;
import com.pro1e.utils.magbox;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import duan1.model.NhanVien;
import java.awt.event.KeyEvent;

/**
 *
 * @author nguye
 */
public class QLNhanVienPN extends javax.swing.JPanel {

    DefaultTableModel model;
    NhanvienDAO nvDAO = new NhanvienDAO();
    List<NhanVien> lsNV;

    /**
     * Creates new form QLNhanVienForm
     */
    public QLNhanVienPN() {
        initComponents();
        lsNV = nvDAO.selectall();
        loadNV();

//        lsNV = nvDAO.selectall();
//        for (NhanVien nhanVien : lsNV) {
//            System.out.println(nhanVien.toString());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        btnquenmk = new javax.swing.JButton();
        btntaonhanvien = new javax.swing.JButton();
        btndanhsach2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pndanhsach = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnhanvien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnquenmk.setBackground(new java.awt.Color(255, 51, 102));
        btnquenmk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnquenmk.setForeground(new java.awt.Color(255, 255, 255));
        btnquenmk.setText("quên mật khẩu");
        btnquenmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquenmkActionPerformed(evt);
            }
        });

        btntaonhanvien.setBackground(new java.awt.Color(255, 51, 102));
        btntaonhanvien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntaonhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btntaonhanvien.setText("TẠO NHÂN VIÊN");
        btntaonhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaonhanvienActionPerformed(evt);
            }
        });

        btndanhsach2.setBackground(new java.awt.Color(255, 51, 102));
        btndanhsach2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndanhsach2.setForeground(new java.awt.Color(255, 255, 255));
        btndanhsach2.setText("Gửi MAIL ");
        btndanhsach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhsach2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntaonhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 583, Short.MAX_VALUE)
                .addComponent(btnquenmk, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndanhsach2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndanhsach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntaonhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquenmk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setLayout(new java.awt.CardLayout());

        pndanhsach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimkiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttimkiemKeyTyped(evt);
            }
        });

        tbnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TÊN ", "ID BAN", "SDT", "EMAIL", "QUYỀN", "CMND"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnhanvien);
        if (tbnhanvien.getColumnModel().getColumnCount() > 0) {
            tbnhanvien.getColumnModel().getColumn(0).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(1).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(2).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(3).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(4).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TìM kIẾM");

        javax.swing.GroupLayout pndanhsachLayout = new javax.swing.GroupLayout(pndanhsach);
        pndanhsach.setLayout(pndanhsachLayout);
        pndanhsachLayout.setHorizontalGroup(
            pndanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pndanhsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        pndanhsachLayout.setVerticalGroup(
            pndanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndanhsachLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pndanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel4.add(pndanhsach, "card2");

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 1100, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnquenmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquenmkActionPerformed
        int[] rowselect = tbnhanvien.getSelectedRows();
   
        for (int i = 0; i < rowselect.length; i++) {
           String mailTo = lsNV.get(rowselect[i]).getEmail();
             String body = "  người dùng: " + lsNV.get(i).getTenNV() + "\n mật khẩu :" + lsNV.get(i).getMatKhau();
               SEnDMAIL smail = new SEnDMAIL(mailTo);
              smail.sendEmail("Thư thông báo mật khẩu EVENT MANAGER", body);
        }
      

//       NhanVien getNV = lsNV.get(tbnhanvien.getSelectedRow());
//        SEnDMAIL smail = new SEnDMAIL(getNV.getEmail());
//        String body = "  người dùng: " + getNV.getTenNV() + "\n mật khẩu :" + getNV.getMatKhau();
//        smail.sendEmail("Thư thông báo mật khẩu EVENT MANAGER", body);
//        magbox.mgbox(this, "đã gửi thư thông báo mật khẩu về mail");
    }//GEN-LAST:event_btnquenmkActionPerformed

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void txttimkiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyTyped
        if (txttimkiem.getText().equals("")) {
            lsNV = nvDAO.selectall();
            loadNV();
        }
    }//GEN-LAST:event_txttimkiemKeyTyped

    private void txttimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String keyW = txttimkiem.getText();
            lsNV = nvDAO.timKiemNV(keyW);
            loadNV();
        }
    }//GEN-LAST:event_txttimkiemKeyPressed

    private void tbnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnhanvienMouseClicked
        if (evt.getClickCount() == 2) {
            new TAOnhanvien(this, false, lsNV.get(tbnhanvien.rowAtPoint(evt.getPoint()))).setVisible(true);
        }
    }//GEN-LAST:event_tbnhanvienMouseClicked

    private void btntaonhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaonhanvienActionPerformed
        new TAOnhanvien(this, true, new NhanVien()).setVisible(true); // if true is tạo nhân viên
    }//GEN-LAST:event_btntaonhanvienActionPerformed

    private void btndanhsach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhsach2ActionPerformed
        int[] rowselect = tbnhanvien.getSelectedRows();
        String mailTo = "";
        for (int i = 0; i < rowselect.length; i++) {
            mailTo += lsNV.get(rowselect[i]).getEmail();
            if (i < rowselect.length - 1) {
                mailTo += ",";
            }
        }
        System.out.println(mailTo);
        new SEnDMAIL(mailTo).setVisible(true);
    }//GEN-LAST:event_btndanhsach2ActionPerformed
    void taoANDload() {
        lsNV = nvDAO.selectall();
        loadNV();
    }

    void loadNV() {

        model = (DefaultTableModel) tbnhanvien.getModel();
        model.setRowCount(0);
        for (NhanVien e : lsNV) {
            model.addRow(new Object[]{
                e.getTenNV(), e.getIdBan(), e.getSdt(), e.getEmail(), (e.getQuyen() == 0 ? "Quản lý" : "nhân viên"), e.getCmnd()
            });
            // System.out.println(e.toString1());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanhsach2;
    private javax.swing.JButton btnquenmk;
    private javax.swing.JButton btntaonhanvien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pndanhsach;
    private javax.swing.JTable tbnhanvien;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
