/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.DAO.NhanvienDAO;
import com.pro1e.helper.JDBChelper;
import com.pro1e.utils.magbox;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import duan1.model.NhanVien;
import java.awt.event.KeyEvent;

/**
 *
 * @author nguye
 */
public class QLNhanVienPN extends javax.swing.JPanel {

    DefaultTableModel model;
    NhanvienDAO nvDAO = new NhanvienDAO();
    List<NhanVien> lsNV;
    
    /**
     * Creates new form QLNhanVienForm
     */
    public QLNhanVienPN() {
        initComponents();
        lsNV = nvDAO.selectall();
        loadNV();
        
//        lsNV = nvDAO.selectall();
//        for (NhanVien nhanVien : lsNV) {
//            System.out.println(nhanVien.toString());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        btndanhsach = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pndanhsach = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnhanvien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btndanhsach.setBackground(new java.awt.Color(255, 51, 102));
        btndanhsach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndanhsach.setForeground(new java.awt.Color(255, 255, 255));
        btndanhsach.setText("TẠO NHÂN VIÊN");
        btndanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhsachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btndanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 877, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndanhsach, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setLayout(new java.awt.CardLayout());

        pndanhsach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimkiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttimkiemKeyTyped(evt);
            }
        });

        tbnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TÊN ", "Mật Khẩu", "ID BAN", "SDT", "EMAIL", "QUYỀN", "CMND"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnhanvien);
        if (tbnhanvien.getColumnModel().getColumnCount() > 0) {
            tbnhanvien.getColumnModel().getColumn(0).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(1).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(2).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(3).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(4).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(5).setResizable(false);
            tbnhanvien.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TìM kIẾM");

        javax.swing.GroupLayout pndanhsachLayout = new javax.swing.GroupLayout(pndanhsach);
        pndanhsach.setLayout(pndanhsachLayout);
        pndanhsachLayout.setHorizontalGroup(
            pndanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pndanhsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        pndanhsachLayout.setVerticalGroup(
            pndanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pndanhsachLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pndanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel4.add(pndanhsach, "card2");

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 1100, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btndanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhsachActionPerformed
        new TAOnhanvien(this, true,new NhanVien()).setVisible(true); // if true is tạo nhân viên

    }//GEN-LAST:event_btndanhsachActionPerformed
   
    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemKeyReleased
    
    private void txttimkiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyTyped
        if (txttimkiem.getText().equals("")) {
            lsNV = nvDAO.selectall();
            loadNV();
        }
    }//GEN-LAST:event_txttimkiemKeyTyped

    private void txttimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String keyW = txttimkiem.getText();
            lsNV = nvDAO.timKiemNV(keyW);
            loadNV();
        }
    }//GEN-LAST:event_txttimkiemKeyPressed

    private void tbnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnhanvienMouseClicked
        if (evt.getClickCount() == 2) {
            new TAOnhanvien(this, false, lsNV.get(tbnhanvien.rowAtPoint(evt.getPoint()))).setVisible(true);
       }
    }//GEN-LAST:event_tbnhanvienMouseClicked
    void taoANDload(){
          lsNV = nvDAO.selectall();
          loadNV();
    }
    void loadNV() {
      
        model = (DefaultTableModel) tbnhanvien.getModel();
        model.setRowCount(0);
        for (NhanVien e : lsNV) {
            model.addRow(new Object[]{
               
                e.getTenNV(), e.getMatKhau(), e.getIdBan(), e.getSdt(), e.getEmail(), (e.getQuyen() == 0 ? "Quản lý" : "nhân viên"), e.getCmnd()
            });
           // System.out.println(e.toString1());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanhsach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pndanhsach;
    private javax.swing.JTable tbnhanvien;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
