/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pro1e.UI;

import com.pro1e.DAO.SukienDAO;
import com.pro1e.UI.chill.functionIcon;
import com.pro1e.utils.auth;
import duan1.model.SuKien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author huyNQph11019
 */
public class QLsukienPN extends javax.swing.JPanel {

    MainF ro;
    /**
     * Creates new form QLsukien s
     */
    SukienDAO DAOSK = new SukienDAO();
    TAosukien taosk ;
    List<SuKien> lsk= DAOSK.selectall();

    public QLsukienPN(MainF root) {
        initComponents();
        this.ro = root;
        loadsukien();
        auth.curQLsukien = this;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntaosk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1110, 640));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 5));

        btntaosk.setBackground(new java.awt.Color(0, 102, 204));
        btntaosk.setPreferredSize(new java.awt.Dimension(200, 100));
        btntaosk.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pro1e/icon/icons8_add_new_50px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        btntaosk.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TẠO SỰ KIỆN");
        btntaosk.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        add(btntaosk);
    }// </editor-fold>//GEN-END:initComponents
public void addSukien(String  tensk  , MainF pa,SuKien ev) {
        this.add(new functionIcon(tensk, pa,ev));
        this.validate();
    }

    void loadsukien() {
        this.removeAll();
        this.add(btntaosk);
        lsk= DAOSK.selectall();
        lsk.forEach(sk -> {
            addSukien(sk.getTenSK(), ro, sk);
        });
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (taosk== null) {
          taosk =    new TAosukien(ro, this);
          taosk.setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btntaosk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
